<?php
/**
 * Context API implementations
 */
include_once('cmtls_media.contexts.inc');

/**
 * Context API implementations
 */
include_once('cmtls_media.views.inc');

/**
 * Implementation of hook_ctools_plugin_api().
 */
function cmtls_media_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
}

/**
 * Implementation of hook_views_api().
 */
function cmtls_media_views_api() {
  list($module, $api) = func_get_args();
  if ($module == "views" && $api == "views_default") {
    return array("version" => "3.0");
  }
}

/**
 * Implements hook_cmtls_app
 */
function cmtls_media_cmtls_app() {
  return array(
    'cmtls_media' => array(
      'title' => t('Media galleries'),
      'description' => t('Galleries for images, videos and files'),
      'node types' => array(
        'media_gallery' => t('Gallery'),
      ),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * adds autocomplete for the location
 */
function cmtls_media_form_media_gallery_node_form_alter(&$form, &$form_state, $form_id) {
  drupal_add_js(drupal_get_path('module', 'cmtls') . '/js/cmtls.location_ac.js');
}




