<?php
/**
 * @file
 * Code for the CT Media feature.
 */

include_once('cmtls_media.features.inc');

/**
 * Implements hook_cmtls_app
 * 
 * @see cmtls.module
 */
function cmtls_media_cmtls_app() {
  return array(
    'cmtls_media' => array(
      'title' => t('Media galleries'),
      'description' => t('Galleries for images, videos and files'),
      'node types' => array(
        'media_gallery' => t('Gallery'),
      ),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * adds autocomplete for the location
 */
function cmtls_media_form_media_gallery_node_form_alter(&$form, &$form_state, $form_id) {
  drupal_add_js(drupal_get_path('module', 'cmtls_location') . '/js/cmtls.location_ac.js');
}




